[package]
name = "netcode-rs"
version = "0.1.0"
edition = "2024"
authors = ["Zsolt Bölöny <bolony.zsolt@gmail.com>"]
keywords = ["netcode", "udp", "gamedev", "networking"]
description = "Pure Rust implementation of the netcode.io protocol"
license = "MIT"
readme = "README.md"
categories = ["network-programming", "game-development"]
repository = "https://github.com/yzsolt/netcode-rs"

[dependencies]
log = "0.4"
byteorder = "1.5"
chacha20poly1305 = "0.10"
getrandom = "0.4"

[dev-dependencies]
env_logger = "0.11"
